# Generated by Django 2.2.2 on 2019-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190722_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=900),
        ),
    ]
