# Generated by Django 2.2.2 on 2019-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190722_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(max_length=900),
        ),
    ]
